version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=citylink
      - MYSQL_DATABASE=citylink
      - MYSQL_USER=citylink
      - MYSQL_PASSWORD=citylink
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  flyway:
    image: flyway/flyway
    depends_on:
      - db
    command: -url=jdbc:mysql://db:3306/citylink -user=citylink -password=citylink -baselineOnMigrate=true migrate
    volumes:
      - ./migrations:/flyway/sql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_data: